;;; backup-each-save-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from backup-each-save.el

(autoload 'backup-each-save "backup-each-save")
(register-definition-prefixes "backup-each-save" '("backup-each-save-"))

;;; End of scraped data

(provide 'backup-each-save-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; backup-each-save-autoloads.el ends here
