;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-line-dwim
        forward-sexp
        sp--self-insert-command
        yas-expand
        zap-up-to-char
        zap-up-to-non-whitespace
        ))

(setq mc/cmds-to-run-once
      '(
        ag-project-at-point
        smex
        sp-rewrap-sexp
        sp-splice-sexp
        ))
