;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-zap-up-to-char-dwim
        backward-sexp
        beginning-of-line-dwim
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        end-of-visual-line
        forward-sexp
        hungry-delete-forward
        isearch-abort
        jump-char-forward
        jump-char-process-char
        kill-or-delete-region
        markdown-exdent-or-delete
        org-delete-char
        org-self-insert-command
        python-indent-electric-colon
        sgml-slash
        sp--self-insert-command
        sp-remove-active-pair-overlay
        wh/decrement-number-decimal
        wh/increment-number-decimal
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        zap-up-to-char
        zap-up-to-non-whitespace
        ))

(setq mc/cmds-to-run-once
      '(
        ag-project-at-point
        comment-dwim
        helm-M-x
        mouse-set-region
        smex
        sp-rewrap-sexp
        sp-splice-sexp
        ))
