language: emacs-lisp
branches:
  only:
    - gh-pages
env:
  - EVM_EMACS=emacs-24.5-bin
script:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - emacs --version
  - rm -rf ~/.emacs.d
  - cp -r ../.emacs.d ~/.emacs.d
  - emacs --batch --load /home/travis/.emacs.d/init.el
notifications:
  email: false
