#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: jsflikes <your JavaScript file>"
  exit
fi

absolute_path=`readlink -m $1`

cd ~/.emacs.d/user-js/jshint
java -jar ~/.emacs.d/user-js/rhino1_7R2/js.jar env/rhino.js $absolute_path

