;;; tablist-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tablist.el

(autoload 'tablist-minor-mode "tablist"
"Toggle tablist minor mode.

This is a minor mode.  If called interactively, toggle the `Tablist
minor mode' mode.  If the prefix argument is positive, enable the mode,
and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `tablist-minor-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'tablist-mode "tablist"
"Major mode derived from `tabulated-list-mode' by `define-derived-mode'.
It inherits all of the parent's attributes, but has its own keymap,
abbrev table and syntax table:

  `tablist-mode-map', `tablist-mode-abbrev-table' and
`tablist-mode-syntax-table'

which more-or-less shadow tabulated-list-mode's corresponding tables.

In addition to any hooks its parent mode might have run, this mode
runs the hook `tablist-mode-hook', as the final or penultimate step
during initialization.

\\{tablist-mode-map}" t)
(register-definition-prefixes "tablist" '("tab"))


;;; Generated autoloads from tablist-filter.el

(register-definition-prefixes "tablist-filter" '("tablist-filter-"))


;;; End of scraped data

(provide 'tablist-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tablist-autoloads.el ends here
