;;; flycheck-eglot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-eglot.el

(autoload 'flycheck-eglot-mode "flycheck-eglot" "\
Minor mode for using Flycheck with Eglot.

This is a minor mode.  If called interactively, toggle the
`Flycheck-Eglot mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `flycheck-eglot-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-flycheck-eglot-mode 'globalized-minor-mode t)
(defvar global-flycheck-eglot-mode nil "\
Non-nil if Global Flycheck-Eglot mode is enabled.
See the `global-flycheck-eglot-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-flycheck-eglot-mode'.")
(custom-autoload 'global-flycheck-eglot-mode "flycheck-eglot" nil)
(autoload 'global-flycheck-eglot-mode "flycheck-eglot" "\
Toggle Flycheck-Eglot mode in all buffers.
With prefix ARG, enable Global Flycheck-Eglot mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Flycheck-Eglot mode is enabled in all buffers where `(lambda nil (when
(flycheck-eglot--eglot-available-p) (flycheck-eglot-mode 1)))' would
do it.

See `flycheck-eglot-mode' for more information on Flycheck-Eglot
mode.

(fn &optional ARG)" t)
(register-definition-prefixes "flycheck-eglot" '("flycheck-eglot-"))

;;; End of scraped data

(provide 'flycheck-eglot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-eglot-autoloads.el ends here
