language: emacs-lisp
before_install:
  - if [ "$ECUKES_EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
env:
  - ECUKES_EMACS=emacs
script:
  ./run-travis-ci.sh