;;; geiser-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser.el

(defconst geiser-elisp-dir (file-name-directory (or load-file-name buffer-file-name)) "\
Directory containing Geiser's Elisp files.")
(mapc (lambda (group) (custom-add-load group (symbol-name group)) (custom-add-load 'geiser (symbol-name group))) '(geiser geiser-edit geiser-repl geiser-autodoc geiser-doc geiser-debug geiser-faces geiser-mode geiser-image geiser-implementation geiser-xref))


;;; Generated autoloads from geiser-autodoc.el

(register-definition-prefixes "geiser-autodoc" '("geiser-autodoc-"))


;;; Generated autoloads from geiser-base.el

(register-definition-prefixes "geiser-base" '("geiser--"))


;;; Generated autoloads from geiser-capf.el

(register-definition-prefixes "geiser-capf" '("geiser-capf-"))


;;; Generated autoloads from geiser-compile.el

(register-definition-prefixes "geiser-compile" '("geiser-"))


;;; Generated autoloads from geiser-completion.el

(register-definition-prefixes "geiser-completion" '("geiser-"))


;;; Generated autoloads from geiser-connection.el

(register-definition-prefixes "geiser-connection" '("geiser-con"))


;;; Generated autoloads from geiser-custom.el

(register-definition-prefixes "geiser-custom" '("geiser-custom-"))


;;; Generated autoloads from geiser-debug.el

(register-definition-prefixes "geiser-debug" '("geiser-debug-"))


;;; Generated autoloads from geiser-doc.el

(register-definition-prefixes "geiser-doc" '("geiser-doc"))


;;; Generated autoloads from geiser-edit.el

(register-definition-prefixes "geiser-edit" '("geiser-"))


;;; Generated autoloads from geiser-eval.el

(register-definition-prefixes "geiser-eval" '("geiser-eval-"))


;;; Generated autoloads from geiser-image.el

(register-definition-prefixes "geiser-image" '("geiser-"))


;;; Generated autoloads from geiser-impl.el

 (defvar geiser-active-implementations nil)
 (defvar geiser-implementations-alist nil)
(defun geiser-activate-implementation (impl) (add-to-list 'geiser-active-implementations impl))
(defun geiser-impl--add-to-alist (kind what impl &optional append) (add-to-list 'geiser-implementations-alist (list (list kind what) impl) append))
(defun geiser-implementation-extension (impl ext) "\
Add to `geiser-implementations-alist' an entry for extension EXT." (geiser-impl--add-to-alist 'regexp (format "\\.%s\\'" ext) impl t))
(register-definition-prefixes "geiser-impl" '("define-geiser-implementation" "geiser-" "with--geiser-implementation"))


;;; Generated autoloads from geiser-log.el

(register-definition-prefixes "geiser-log" '("geiser-"))


;;; Generated autoloads from geiser-menu.el

(register-definition-prefixes "geiser-menu" '("geiser-menu--"))


;;; Generated autoloads from geiser-mode.el

(autoload 'geiser-mode "geiser-mode" "\
Toggle Geiser's mode.

With no argument, this command toggles the mode.
Non-null prefix argument turns on the mode.
Null prefix argument turns off the mode.

When Geiser mode is enabled, a host of nice utilities for
interacting with the Geiser REPL is at your disposal.
\\{geiser-mode-map}

This is a minor mode.  If called interactively, toggle the
`Geiser mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `geiser-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'turn-on-geiser-mode "geiser-mode" "\
Enable `geiser-mode' (in a Scheme buffer)." t)
(autoload 'geiser-mode--maybe-activate "geiser-mode")
(add-hook 'scheme-mode-hook 'geiser-mode--maybe-activate)
(register-definition-prefixes "geiser-mode" '("geiser-" "turn-off-geiser-mode"))


;;; Generated autoloads from geiser-popup.el

(register-definition-prefixes "geiser-popup" '("geiser-popup-"))


;;; Generated autoloads from geiser-reload.el

(autoload 'geiser-unload "geiser-reload" "\
Unload all Geiser modules." t)
(register-definition-prefixes "geiser-reload" '("geiser-"))


;;; Generated autoloads from geiser-repl.el

(define-obsolete-function-alias 'run-geiser 'geiser "Geiser 0.26")
(autoload 'geiser "geiser-repl" "\
Start a new Geiser REPL.

(fn IMPL)" t)
(autoload 'geiser-connect "geiser-repl" "\
Start a new Geiser REPL connected to a remote Scheme process.

(fn IMPL &optional HOST PORT)" t)
(autoload 'geiser-connect-local "geiser-repl" "\
Start a new Geiser REPL connected to a remote Scheme process
over a Unix-domain socket.

(fn IMPL SOCKET)" t)
(autoload 'geiser-repl-switch "geiser-repl" "\
Switch to running Geiser REPL.

If REPL is the current buffer, switch to the previously used
scheme buffer.

With prefix argument, ask for which one if more than one is running.
If no REPL is running, execute `geiser' to start a fresh one.

(fn &optional ASK IMPL BUFFER)" t)
(register-definition-prefixes "geiser-repl" '("geiser-"))


;;; Generated autoloads from geiser-syntax.el

(register-definition-prefixes "geiser-syntax" '("geiser-syntax--"))


;;; Generated autoloads from geiser-table.el

(register-definition-prefixes "geiser-table" '("geiser-table-"))


;;; Generated autoloads from geiser-xref.el

(register-definition-prefixes "geiser-xref" '("geiser-xref"))

;;; End of scraped data

(provide 'geiser-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-autoloads.el ends here
