;;; cider-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cider.el

(autoload 'cider-version "cider"
"Display CIDER's version." t)
 (autoload 'cider-start-map "cider" "CIDER jack-in and connect keymap." t 'keymap)
 (autoload 'cider-start-menu "cider" "Menu for starting CIDER sessions." t)
(autoload 'cider-connect-sibling-clj "cider"
"Create a Clojure REPL with the same server as OTHER-REPL.
PARAMS is for consistency with other connection commands and is currently
ignored.  OTHER-REPL defaults to `cider-current-repl' and in programs can
also be a server buffer, in which case a new session with a REPL for that
server is created.

(fn PARAMS &optional OTHER-REPL)" t)
(autoload 'cider-connect-sibling-cljs "cider"
"Create a ClojureScript REPL with the same server as OTHER-REPL.
PARAMS is a plist optionally containing :cljs-repl-type (e.g. `node',
`figwheel', `shadow', etc).

All other parameters are inferred from the OTHER-REPL.
OTHER-REPL defaults to `cider-current-repl' but in programs can also be a
server buffer, in which case a new session for that server is created.

(fn PARAMS &optional OTHER-REPL)" t)
(autoload 'cider-connect-clj "cider"
"Initialize a Clojure connection to an nREPL server.
PARAMS is a plist optionally containing :host, :port and :project-dir.
If nil, use the default parameters in `cider-connect-default-params'.

With the prefix argument, prompt for all the parameters regardless of
their supplied or default values.

(fn &optional PARAMS)" t)
(autoload 'cider-connect-cljs "cider"
"Initialize a ClojureScript connection to an nREPL server.
PARAMS is a plist optionally containing :host, :port, :project-dir and
:cljs-repl-type (e.g. `shadow', `node', `figwheel', etc).
If nil, use the default parameters in `cider-connect-default-params' or
`cider-connect-default-cljs-params'.

With the prefix argument, prompt for all the parameters regardless of
their supplied or default values.

(fn &optional PARAMS)" t)
(autoload 'cider-connect-clj&cljs "cider"
"Initialize a Clojure and ClojureScript connection to an nREPL server.
PARAMS is a plist optionally containing :host, :port, :project-dir and
:cljs-repl-type (e.g. `shadow', `node', `figwheel', etc).
If nil, use the default parameters in `cider-connect-default-params' and
`cider-connect-default-cljs-params'.

When SOFT-CLJS-START is non-nil, don't start if ClojureScript requirements are
not met.

With the prefix argument, prompt for all the parameters regardless of
their supplied or default values.

(fn PARAMS &optional SOFT-CLJS-START)" t)
(autoload 'cider "cider"
"Start a connection of any type interactively." t)
(defalias 'cider-jack-in #'cider-jack-in-clj)
(defalias 'cider-connect #'cider-connect-clj)
(autoload 'cider--setup-clojure-major-mode "cider"
"Setup Cider key bindings on a Clojure mode's MODE-MAP and hooks in MODE-HOOK.

(fn MODE-MAP MODE-HOOK)")
(with-eval-after-load 'clojure-mode (cider--setup-clojure-major-mode clojure-mode-map 'clojure-mode-hook))
(with-eval-after-load 'clojure-ts-mode (cider--setup-clojure-major-mode (with-suppressed-warnings ((free-vars clojure-ts-mode-map)) clojure-ts-mode-map) 'clojure-ts-mode-hook))
(register-definition-prefixes "cider" '("cider-"))


;;; Generated autoloads from cider-apropos.el

(autoload 'cider-apropos "cider-apropos"
"Show all symbols whose names match QUERY, a regular expression.
QUERY can also be a list of space-separated words (e.g. take while) which
will be converted to a regular expression (like take.+while) automatically
behind the scenes.  The search may be limited to the namespace NS, and may
optionally search doc strings (based on DOCS-P), include private vars
(based on PRIVATES-P), and be case-sensitive (based on CASE-SENSITIVE-P).

(fn QUERY &optional NS DOCS-P PRIVATES-P CASE-SENSITIVE-P)" t)
(autoload 'cider-apropos-documentation "cider-apropos"
"Shortcut for (cider-apropos <query> nil t)." t)
(autoload 'cider-apropos-select "cider-apropos"
"Similar to `cider-apropos', but presents the results in a completing read.
Show all symbols whose names match QUERY, a regular expression.
QUERY can also be a list of space-separated words (e.g. take while) which
will be converted to a regular expression (like take.+while) automatically
behind the scenes.  The search may be limited to the namespace NS, and may
optionally search doc strings (based on DOCS-P), include private vars
(based on PRIVATES-P), and be case-sensitive (based on CASE-SENSITIVE-P).

(fn QUERY &optional NS DOCS-P PRIVATES-P CASE-SENSITIVE-P)" t)
(autoload 'cider-apropos-documentation-select "cider-apropos"
"Shortcut for (cider-apropos-select <query> nil t)." t)
(register-definition-prefixes "cider-apropos" '("cider-"))


;;; Generated autoloads from cider-browse-ns.el

(autoload 'cider-browse-ns "cider-browse-ns"
"List all NAMESPACE's vars.

(fn NAMESPACE)" t)
(autoload 'cider-browse-ns-all "cider-browse-ns"
"List all loaded namespaces." t)
(register-definition-prefixes "cider-browse-ns" '("cider-browse-ns-"))


;;; Generated autoloads from cider-browse-spec.el

(autoload 'cider-browse-spec "cider-browse-spec"
"Browse SPEC definition.

(fn SPEC)" t)
(autoload 'cider-browse-spec-all "cider-browse-spec"
"Open list of specs in a popup buffer.

With a prefix argument ARG, prompts for a regexp to filter specs.
No filter applied if the regexp is the empty string.

(fn &optional ARG)" t)
(autoload 'cider-browse-spec-tree "cider-browse-spec"
"Browse SPEC and the specs it references as an interactive tree.
Each node expands to the namespaced specs that spec depends on - fetched a level
at a time - so you can walk a spec's structure in place; \\<cider-tree-view-mode-map>\\[cider-tree-view-visit] on a node
shows that spec's full definition.

(fn SPEC)" t)
(register-definition-prefixes "cider-browse-spec" '("cider-"))


;;; Generated autoloads from cider-cheatsheet.el

(autoload 'cider-cheatsheet-select "cider-cheatsheet"
"Navigate cheatsheet sections and show documentation for selected var.

With a prefix argument FLAT, represent each candidate as a full path to var.

(fn &optional FLAT)" t)
(autoload 'cider-cheatsheet "cider-cheatsheet"
"Display cheatsheet in a popup buffer." t)
(register-definition-prefixes "cider-cheatsheet" '("cider-cheatsheet-"))


;;; Generated autoloads from cider-classpath.el

(autoload 'cider-classpath "cider-classpath"
"List all classpath entries." t)
(autoload 'cider-open-classpath-entry "cider-classpath"
"Open a classpath entry." t)
(register-definition-prefixes "cider-classpath" '("cider-classpath-"))


;;; Generated autoloads from cider-client.el

(register-definition-prefixes "cider-client" '("cider-"))


;;; Generated autoloads from cider-cljs.el

(register-definition-prefixes "cider-cljs" '("cider-"))


;;; Generated autoloads from cider-clojuredocs.el

(autoload 'cider-clojuredocs-web "cider-clojuredocs"
"Open ClojureDocs documentation in the default web browser.

Prompts for the symbol to use, or uses the symbol at point, depending on
the value of `cider-prompt-for-symbol'.  With prefix arg ARG, does the
opposite of what that option dictates.

(fn &optional ARG)" t)
(autoload 'cider-clojuredocs-refresh-cache "cider-clojuredocs"
"Refresh the ClojureDocs cache." t)
(autoload 'cider-clojuredocs "cider-clojuredocs"
"Open ClojureDocs documentation in a popup buffer.

Prompts for the symbol to use, or uses the symbol at point, depending on
the value of `cider-prompt-for-symbol'.  With prefix arg ARG, does the
opposite of what that option dictates.

(fn &optional ARG)" t)
(register-definition-prefixes "cider-clojuredocs" '("cider-"))


;;; Generated autoloads from cider-common.el

(register-definition-prefixes "cider-common" '("cider-"))


;;; Generated autoloads from cider-compilation.el

(register-definition-prefixes "cider-compilation" '("cider-"))


;;; Generated autoloads from cider-completion.el

(register-definition-prefixes "cider-completion" '("cider-"))


;;; Generated autoloads from cider-completion-context.el

(register-definition-prefixes "cider-completion-context" '("cider-completion-"))


;;; Generated autoloads from cider-connection.el

(register-definition-prefixes "cider-connection" '("cider-"))


;;; Generated autoloads from cider-debug.el

(autoload 'cider-debug-defun-at-point "cider-debug"
"Instrument the \"top-level\" expression at point.
If it is a defn, dispatch the instrumented definition.  Otherwise,
immediately evaluate the instrumented expression.

While debugged code is being evaluated, the user is taken through the
source code and displayed the value of various expressions.  At each step,
a number of keys will be prompted to the user." t)
(register-definition-prefixes "cider-debug" '("cider-"))


;;; Generated autoloads from cider-doc.el

 (autoload 'cider-doc-menu "cider-doc" "Menu for CIDER's documentation commands." t)
(register-definition-prefixes "cider-doc" '("cider-"))


;;; Generated autoloads from cider-docstring.el

(register-definition-prefixes "cider-docstring" '("cider-"))


;;; Generated autoloads from cider-doctor.el

(autoload 'cider-doctor "cider-doctor"
"Diagnose the current CIDER setup and show a report.
Runs offline environment checks and, when a REPL is connected, a set of
connection-health checks.  The resulting buffer is meant to be pasted
into bug reports.  Press \\<cider-doctor-mode-map>\\[revert-buffer] to
refresh it." t)
(register-definition-prefixes "cider-doctor" '("cider-doctor-"))


;;; Generated autoloads from cider-eldoc.el

(register-definition-prefixes "cider-eldoc" '("cider-"))


;;; Generated autoloads from cider-endpoint.el

(register-definition-prefixes "cider-endpoint" '("cider-"))


;;; Generated autoloads from cider-enlighten.el

(defvar cider-enlighten-mode nil
"Non-nil if Cider-Enlighten mode is enabled.
See the `cider-enlighten-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `cider-enlighten-mode'.")
(custom-autoload 'cider-enlighten-mode "cider-enlighten" nil)
(autoload 'cider-enlighten-mode "cider-enlighten"
"Minor mode for displaying locals in debugger-instrumented evaluations.

This is a global minor mode.  If called interactively, toggle the
`Cider-Enlighten mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='cider-enlighten-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'cider-enlighten-defun-at-point "cider-enlighten"
"Evaluate the top-level form at point with enlightenment enabled.
This is like enabling `cider-enlighten-mode' and evaluating the form, but
scoped to this single evaluation, so you needn't toggle the global mode on
and off (and re-evaluate everything) just to light up one definition." t)
(autoload 'cider-enlighten-clear "cider-enlighten"
"Remove all enlighten value overlays from the current buffer." t)
(autoload 'cider-enlighten-stop "cider-enlighten"
"Stop displaying enlighten overlays, without re-evaluating anything.
Turn off `cider-enlighten-mode', remove the existing overlays, and ignore
any further enlighten values still streaming from previously-instrumented
code.  This quiets things down at once - unlike disabling the mode alone,
which leaves already-instrumented definitions lighting up every time they
run.  Re-enabling the mode (or `cider-enlighten-defun-at-point') resumes
display." t)
(register-definition-prefixes "cider-enlighten" '("cider-"))


;;; Generated autoloads from cider-eval.el

 (autoload 'cider-eval-pprint-menu "cider-eval" "Menu for CIDER's pretty-printing eval commands." t)
 (autoload 'cider-eval-menu "cider-eval" "Menu for CIDER's evaluation commands." t)
(register-definition-prefixes "cider-eval" '("cider-"))


;;; Generated autoloads from cider-find.el

(autoload 'cider-find-var "cider-find"
"Find definition for VAR at LINE.
Prompt according to prefix ARG and `cider-prompt-for-symbol'.
A single or double prefix argument inverts the meaning of
`cider-prompt-for-symbol'.  A prefix of `-` or a double prefix argument causes
the results to be displayed in a different window.  The default value is
thing at point.

(fn &optional ARG VAR LINE)" t)
(autoload 'cider-find-dwim-at-mouse "cider-find"
"Find and display variable or resource at mouse EVENT.

(fn EVENT)" t)
(autoload 'cider-find-dwim "cider-find"
"Find and display the SYMBOL-FILE at point.
SYMBOL-FILE could be a var or a resource.  If thing at point is empty then
show Dired on project.  If var is not found, try to jump to resource of the
same name.  When called interactively, a prompt is given according to the
variable `cider-prompt-for-symbol'.  A single or double prefix argument
inverts the meaning.  A prefix of `-' or a double prefix argument causes
the results to be displayed in a different window.  A default value of thing
at point is given when prompted.

(fn SYMBOL-FILE)" t)
(autoload 'cider-find-resource "cider-find"
"Find the resource at PATH.
Prompt for input as indicated by the variable `cider-prompt-for-symbol'.
A single or double prefix argument inverts the meaning of
`cider-prompt-for-symbol'.  A prefix argument of `-` or a double prefix
argument causes the results to be displayed in other window.  The default
value is thing at point.

(fn PATH)" t)
(autoload 'cider-find-ns "cider-find"
"Find the file containing NS.
A prefix ARG of `-` or a double prefix argument causes
the results to be displayed in a different window.

(fn &optional ARG NS)" t)
(autoload 'cider-find-keyword "cider-find"
"Find the namespace of the keyword at point and its primary occurrence there.

For instance - if the keyword at point is \":cider.demo/keyword\", this command
would find the namespace \"cider.demo\" and afterwards find the primary
(most relevant or first) mention of \"::keyword\" there.

Prompt according to prefix ARG and `cider-prompt-for-symbol'.
A single or double prefix argument inverts the meaning of
`cider-prompt-for-symbol'.  A prefix of `-` or a double prefix argument causes
the results to be displayed in a different window.  The default value is
thing at point.

(fn &optional ARG)" t)
(register-definition-prefixes "cider-find" '("cider-"))


;;; Generated autoloads from cider-format.el

(autoload 'cider-format-region "cider-format"
"Format the Clojure code in the current region.
START and END represent the region's boundaries.

(fn START END)" t)
(autoload 'cider-format-defun-at-point "cider-format"
"Format the code in the current defun." t)
(autoload 'cider-format-buffer "cider-format"
"Format the Clojure code in the current buffer." t)
(autoload 'cider-format-edn-buffer "cider-format"
"Format the EDN data in the current buffer." t)
(autoload 'cider-format-edn-region "cider-format"
"Format the EDN data in the current region.
START and END represent the region's boundaries.

(fn START END)" t)
(autoload 'cider-format-edn-last-sexp "cider-format"
"Format the EDN data of the sexp preceding point." t)
(register-definition-prefixes "cider-format" '("cider-"))


;;; Generated autoloads from cider-history.el

(autoload 'cider-history "cider-history"
"Display items in the CIDER command history in another buffer." t)
(define-obsolete-function-alias 'cider-repl-history 'cider-history "2.0.0")
(register-definition-prefixes "cider-history" '("cider-history-"))


;;; Generated autoloads from cider-inspector.el

(autoload 'cider--type-tag-at-point "cider-inspector"
"Return the class name of the type tag at point, or nil.
A type tag is a symbol preceded by `^', e.g. the `String' in `^String x'.
This lets the inspector act on the tagged class directly, the way
`cider-doc' does, instead of reading the form the tag applies to (#3679).")
(autoload 'cider-inspect-defun-at-point "cider-inspector"
"Inspect the result of the \"top-level\" expression at point." t)
(autoload 'cider-inspect-sexp-at-point "cider-inspector"
"Inspect the result of the expression around point." t)
(autoload 'cider-inspect-last-result "cider-inspector"
"Inspect the most recent eval result." t)
(autoload 'cider-inspect "cider-inspector"
"Inspect the result of the preceding sexp.

With a prefix argument ARG it inspects the result of the \"top-level\" form.
With a second prefix argument it prompts for an expression to eval and inspect.

Each of those is also a command of its own - `cider-inspect-last-sexp',
`cider-inspect-defun-at-point' and `cider-inspect-expr' - and
`cider-inspect-menu' lists them all, along with
`cider-inspect-sexp-at-point', which this command has no prefix for.

(fn &optional ARG)" t)
(autoload 'cider-inspect-expr "cider-inspector"
"Evaluate EXPR in NS and inspect its value.
Interactively, EXPR is read from the minibuffer, and NS the
current buffer's namespace.

(fn EXPR NS)" t)
(register-definition-prefixes "cider-inspector" '("cider-"))


;;; Generated autoloads from cider-inspiration.el

(register-definition-prefixes "cider-inspiration" '("cider-"))


;;; Generated autoloads from cider-jack-in.el

(autoload 'cider-jack-in-clj "cider-jack-in"
"Start an nREPL server for the current project and connect to it.
PARAMS is a plist optionally containing :project-dir and :jack-in-cmd.
With the prefix argument, allow editing of the jack in command; with a
double prefix prompt for all these parameters.

(fn PARAMS)" t)
(autoload 'cider-jack-in-cljs "cider-jack-in"
"Start an nREPL server for the current project and connect to it.
PARAMS is a plist optionally containing :project-dir, :jack-in-cmd and
:cljs-repl-type (e.g. `shadow', `node', `figwheel', etc).

With the prefix argument,
allow editing of the jack in command; with a double prefix prompt for all
these parameters.

(fn PARAMS)" t)
(autoload 'cider-jack-in-clj&cljs "cider-jack-in"
"Start an nREPL server and connect with clj and cljs REPLs.
PARAMS is a plist optionally containing :project-dir, :jack-in-cmd and
:cljs-repl-type (e.g. `shadow', `node', `figwheel', etc).

With the prefix argument, allow for editing of the jack in command;
with a double prefix prompt for all these parameters.

When SOFT-CLJS-START is non-nil, start cljs REPL
only when the ClojureScript dependencies are met.

(fn &optional PARAMS SOFT-CLJS-START)" t)
(autoload 'cider-jack-in-universal "cider-jack-in"
"Start and connect to an nREPL server for the current project or ARG project id.

If a project is found in current dir, call `cider-jack-in' passing ARG as
first parameter, of which see.  Otherwise, ask user which project type to
start an nREPL server and connect to without a project.

But if invoked with a numeric prefix ARG, then start an nREPL server for
the project type denoted by ARG number and connect to it, even if there is
no project for it in the current dir.

The supported project tools are those in `cider-jack-in-tools' that have a
:dispatch-prefix-arg key.

You can pass a numeric prefix argument n with `M-n` or `C-u n`.

For example, to jack in to leiningen which is assigned to prefix arg 2 type

M-2 \\[cider-jack-in-universal].

(fn ARG)" t)
(register-definition-prefixes "cider-jack-in" '("cider-"))


;;; Generated autoloads from cider-log.el

(autoload 'cider-log-info "cider-log"
"Show the current log buffer, framework, appender and consumer." t)
 (autoload 'cider-log-framework "cider-log" "Show the Cider log framework menu." t)
 (autoload 'cider-log-appender "cider-log" "Show the Cider log appender menu." t)
 (autoload 'cider-log-consumer "cider-log" "Show the Cider log consumer menu." t)
 (autoload 'cider-log-event "cider-log" "Show the Cider log event menu." t)
(autoload 'cider-log-show "cider-log"
"Make the *cider-log* buffer visible.
Set up a framework, appender and consumer if necessary.

Honors the `cider-log-framework-name' customization variable.

This function is offered as an alternative to workflows
based on `transient-mode'." t)
 (autoload 'cider-log "cider-log" "Show the Cider log menu." t)
(register-definition-prefixes "cider-log" '("cider-"))


;;; Generated autoloads from cider-macroexpansion.el

(autoload 'cider-macroexpand-1 "cider-macroexpansion"
"Invoke \\=`macroexpand-1\\=` on the expression preceding point.
If invoked with a PREFIX argument, use \\=`macroexpand\\=` instead of
\\=`macroexpand-1\\=`.

(fn &optional PREFIX)" t)
(autoload 'cider-macroexpand-all "cider-macroexpansion"
"Invoke \\=`macroexpand-all\\=` on the expression preceding point.
The form's head needn't be a macro itself, since a fully-recursive
expansion can reach macros in nested sub-forms." t)
(autoload 'cider-macroexpand-1-at-point "cider-macroexpansion"
"Invoke \\=`macroexpand-1\\=` on the call form around point.
The target is the form at point, widened to the enclosing call when point
is on a bare symbol: an expansion needs a call form.
If invoked with a PREFIX argument, use \\=`macroexpand\\=` instead.

(fn &optional PREFIX)" t)
(autoload 'cider-macroexpand-all-at-point "cider-macroexpansion"
"Invoke \\=`macroexpand-all\\=` on the call form around point.
The target is the form at point, widened to the enclosing call when point
is on a bare symbol." t)
 (autoload 'cider-macroexpand-map "cider-macroexpansion" "CIDER macroexpansion keymap." nil 'keymap)
 (autoload 'cider-macroexpand-menu "cider-macroexpansion" "Menu for CIDER's macroexpansion commands." t)
(register-definition-prefixes "cider-macroexpansion" '("cider-"))


;;; Generated autoloads from cider-macrostep.el

(autoload 'cider-macrostep-expand "cider-macrostep"
"Expand the macro form before point one step, inline.
Place point right after the form, as with `\\[cider-eval-last-sexp]'.  When
point is on a highlighted expandable operator - where `n'/`p' land it - that
operator's form is expanded, so you can step with `n' then expand without
repositioning.

Start a `cider-macrostep-mode' session when one isn't active; further
expansions and collapses then use that mode's key bindings." t)
(autoload 'cider-macrostep-expand-all "cider-macrostep"
"Fully expand the form before point, inline.
Unlike `cider-macrostep-expand', which expands one level at a time, this
expands the form all the way (`macroexpand-all'), so you needn't step through
every level.  Place point right after the form, as with
`\\[cider-eval-last-sexp]'.

Like `cider-macrostep-expand', this starts a `cider-macrostep-mode' session
when one isn't active, and expands the form of the expandable operator at
point when `n'/`p' has landed there.  It does not require the form's head to
be a macro, since a fully-recursive expansion can reach macros in nested
sub-forms." t)
(autoload 'cider-macrostep-expand-in-buffer "cider-macrostep"
"Step through the macro before point in a dedicated buffer.
Like `cider-macrostep-expand', but instead of rewriting the form in place it
copies it into a separate `cider-macrostep-buffer' and starts the stepping
session there, leaving the source buffer untouched.  Place point right after
the form, as with `\\[cider-eval-last-sexp]'.

The session uses the same overlay engine and key bindings as the inline
flow, except that `q' dismisses the whole popup in one step." t)
(register-definition-prefixes "cider-macrostep" '("cider-macrostep-"))


;;; Generated autoloads from cider-mode.el

(defvar cider-mode-line '(:eval (concat (format " cider[%s]" (cider--modeline-info)) (cider-ns-state--lighter)))
"Mode line lighter for cider mode.

The value of this variable is a mode line template as in
`mode-line-format'.  See Info Node `(elisp)Mode Line Format' for details
about mode line templates.

Customize this variable to change how cider mode displays its status in the
mode line.  The default value displays the current connection.  Set this
variable to nil to disable the mode line entirely.")
(custom-autoload 'cider-mode-line "cider-mode" t)
 (autoload 'cider-insert-menu "cider-mode" "Menu for inserting forms into the REPL." t)
 (autoload 'cider-ns-menu "cider-mode" "Menu for CIDER's namespace commands." t)
 (autoload 'cider-menu "cider-mode" "Top-level transient menu for CIDER." t)
(autoload 'cider--setup-menu-for-clojure-major-mode "cider-mode"
"Setup a Cider menu for a Clojure major mode's MODE-MAP.

This menu works as an easy entry-point into CIDER.  Even if cider.el isn't
loaded yet, this will be shown in Clojure buffers next to the Clojure menu.

(fn MODE-MAP)")
(with-eval-after-load 'clojure-mode (cider--setup-menu-for-clojure-major-mode clojure-mode-map))
(with-eval-after-load 'clojure-ts-mode (cider--setup-menu-for-clojure-major-mode (with-suppressed-warnings ((free-vars clojure-ts-mode-map)) clojure-ts-mode-map)))
(autoload 'cider-mode "cider-mode"
"Minor mode for REPL interaction from a Clojure buffer.

\\{cider-mode-map}

This is a minor mode.  If called interactively, toggle the `Cider mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `cider-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "cider-mode" '("cider-"))


;;; Generated autoloads from cider-ns.el

(autoload 'cider-ns-reload "cider-ns"
"Send a (require \\='ns :reload) to the REPL.

With an argument PROMPT, it prompts for a namespace name.  This is the
Clojure out of the box reloading experience and does not rely on
org.clojure/tools.namespace.  See Commentary of this file for a longer list
of differences.  From the Clojure doc: \":reload forces loading of all the
identified libs even if they are already loaded\".

(fn &optional PROMPT)" t)
(autoload 'cider-ns-reload-all "cider-ns"
"Send a (require \\='ns :reload-all) to the REPL.

With an argument PROMPT, it prompts for a namespace name.  This is the
Clojure out of the box reloading experience and does not rely on
org.clojure/tools.namespace.  See Commentary of this file for a longer list
of differences.  From the Clojure doc: \":reload-all implies :reload and
also forces loading of all libs that the identified libs directly or
indirectly load via require\".

(fn &optional PROMPT)" t)
(autoload 'cider-ns-refresh "cider-ns"
"Reload modified and unloaded namespaces, using the Reloaded Workflow.
Uses the configured refresh dirs (defaults to the classpath dirs).

With a single prefix argument, or if MODE is `refresh-all', reload all
namespaces on the classpath dirs unconditionally.

With a double prefix argument, or if MODE is `clear', clear the state of
the namespace tracker before reloading.  This is useful for recovering from
some classes of error (for example, those caused by circular dependencies)
that a normal reload would not otherwise recover from.  The trade-off of
clearing is that stale code from any deleted files may not be completely
unloaded.

With a negative prefix argument, or if MODE is `inhibit-fns', prevent any
refresh functions (defined in `cider-ns-refresh-before-fn' and
`cider-ns-refresh-after-fn') from being invoked.

MODE may also be a list combining these symbols (e.g. \\='(refresh-all
inhibit-fns)), which is how `cider-ns-menu' passes its arguments.

(fn &optional MODE)" t)
(register-definition-prefixes "cider-ns" '("cider-ns-"))


;;; Generated autoloads from cider-ns-state.el

(register-definition-prefixes "cider-ns-state" '("cider-ns-"))


;;; Generated autoloads from cider-overlays.el

(register-definition-prefixes "cider-overlays" '("cider-"))


;;; Generated autoloads from cider-popup.el

(register-definition-prefixes "cider-popup" '("cider-"))


;;; Generated autoloads from cider-profile.el

 (autoload 'cider-profile-map "cider-profile" "CIDER profiling keymap." nil 'keymap)
 (autoload 'cider-profile-menu "cider-profile" "Menu for CIDER's profiling commands." t)
(autoload 'cider-profile-ns-toggle "cider-profile"
"Toggle profiling for the ns associated with optional QUERY.

If optional argument QUERY is non-nil, prompt for ns.  Otherwise use
current ns.

(fn &optional QUERY)" t)
(autoload 'cider-profile-toggle "cider-profile"
"Toggle profiling for a var.
Defaults to the symbol at point.  With a prefix arg QUERY, or when there is
no symbol at point, prompt for the var.

(fn QUERY)" t)
(autoload 'cider-profile-summary "cider-profile"
"Display a summary of currently collected profile data." t)
(autoload 'cider-profile-clear "cider-profile"
"Clear any collected profile data." t)
(register-definition-prefixes "cider-profile" '("cider-profile-"))


;;; Generated autoloads from cider-repl.el

(autoload 'cider-repl-help "cider-repl"
"Display a quick REPL reference for working in the CIDER REPL." t)
(autoload 'cider-repl-describe-startup "cider-repl"
"Describe how the current REPL was started.
Shows the project, endpoint and REPL type, plus the jack-in command and (for
ClojureScript) the init form used to upgrade the REPL - the launch details kept
out of the transcript.  Offers buttons to copy a command or form to the kill
ring (to paste into a shell or the REPL) and to customize the related options." t)
(register-definition-prefixes "cider-repl" '("cider-"))


;;; Generated autoloads from cider-resolve.el

(register-definition-prefixes "cider-resolve" '("cider-resolve-"))


;;; Generated autoloads from cider-scratch.el

(autoload 'cider-scratch "cider-scratch"
"Go to the scratch buffer attached to the current session.
Each session gets its own scratch buffer, permanently attached to it, so
evaluations always target a known session.  When the current context has
no clear session (or when ASK is non-nil - interactively, a prefix
argument), prompt for one.  With no connections at all, fall back to a
single session-less scratch buffer.

(fn &optional ASK)" t)
(register-definition-prefixes "cider-scratch" '("cider-"))


;;; Generated autoloads from cider-selector.el

(autoload 'cider-selector "cider-selector"
"Select a new buffer by type, indicated by a single character.
The user is prompted for a single character indicating the method by
which to choose a new buffer.  The `?' character describes the
available methods.  OTHER-WINDOW provides an optional target.
See `def-cider-selector-method' for defining new methods.

(fn &optional OTHER-WINDOW)" t)
(register-definition-prefixes "cider-selector" '("cider-selector-" "def-cider-selector-method"))


;;; Generated autoloads from cider-session.el

(register-definition-prefixes "cider-session" '("cider-"))


;;; Generated autoloads from cider-stacktrace.el

(register-definition-prefixes "cider-stacktrace" '("cider-"))


;;; Generated autoloads from cider-tap.el

(autoload 'cider-tap "cider-tap"
"Open a buffer that streams values sent to `tap>'.
Any `(tap> value)' in your code - or the inspector's tap commands - shows up
here; press \\<cider-tap-mode-map>\\[cider-tap-inspect-at-point] on an entry to
inspect it.  Killing the buffer stops the streaming." t)
(register-definition-prefixes "cider-tap" '("cider-tap-"))


;;; Generated autoloads from cider-test.el

 (autoload 'cider-test-menu "cider-test" "Menu for CIDER's test commands." t)
(defvar cider-auto-test-mode nil
"Non-nil if Cider-Auto-Test mode is enabled.
See the `cider-auto-test-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `cider-auto-test-mode'.")
(custom-autoload 'cider-auto-test-mode "cider-test" nil)
(autoload 'cider-auto-test-mode "cider-test"
"Toggle automatic testing of Clojure files.

When enabled this reruns tests every time a Clojure file is loaded.
Only runs tests corresponding to the loaded file's namespace and does
nothing if no tests are defined or if the file failed to load.

This is a global minor mode.  If called interactively, toggle the
`Cider-Auto-Test mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='cider-auto-test-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "cider-test" '("cider-"))


;;; Generated autoloads from cider-tracing.el

(autoload 'cider-toggle-trace-var "cider-tracing"
"Toggle var tracing.
Prompts for the symbol to use, or uses the symbol at point, depending on
the value of `cider-prompt-for-symbol'.  With prefix arg ARG, does the
opposite of what that option dictates.

(fn ARG)" t)
(autoload 'cider-toggle-trace-ns "cider-tracing"
"Toggle ns tracing.
Defaults to the current ns.  With prefix arg QUERY, prompts for a ns.

(fn QUERY)" t)
(autoload 'cider-list-traced "cider-tracing"
"Display the vars and namespaces that are currently traced." t)
(autoload 'cider-untrace-all "cider-tracing"
"Untrace all currently traced vars and namespaces." t)
(autoload 'cider-trace "cider-tracing"
"Open a buffer that streams trace events for traced functions.
Trace functions with `cider-toggle-trace-var' or `cider-toggle-trace-ns'
and call them; their calls and return values stream here instead of
cluttering the REPL.  Killing the buffer stops the streaming." t)
 (autoload 'cider-trace-menu "cider-tracing" "Menu for CIDER's tracing commands." t)
(register-definition-prefixes "cider-tracing" '("cider-"))


;;; Generated autoloads from cider-tree-view.el

(register-definition-prefixes "cider-tree-view" '("cider-tree-view-"))


;;; Generated autoloads from cider-util.el

(autoload 'cider-view-manual "cider-util"
"View the manual in your default browser." t)
(register-definition-prefixes "cider-util" '("cider-"))


;;; Generated autoloads from cider-xref.el

(autoload 'cider-xref-fn-refs "cider-xref"
"Show all functions that reference the var matching NS and SYMBOL.

(fn &optional NS SYMBOL)" t)
(autoload 'cider-xref-fn-refs-in-source "cider-xref"
"Show references to SYMBOL found by scanning the project's source files.
Unlike `cider-xref-fn-refs', which introspects the runtime and only sees loaded
namespaces, this scans the files on disk, so it also finds references in code
that hasn't been evaluated yet.  When a REPL is connected SYMBOL is resolved to
its canonical namespace first; otherwise the search falls back to matching the
bare name and is correspondingly more approximate.

The results are textual matches and can include false positives such as
shadowing locals or same-named vars from a different namespace.

(fn &optional SYMBOL)" t)
(autoload 'cider-who-macroexpands "cider-xref"
"Show the use sites of the macro SYMBOL by scanning the project's source.
Macro calls are expanded away at compile time, so the runtime `fn-refs' op (and
hence `cider-who-calls') can't see them; this finds them textually instead, the
same way `cider-xref-fn-refs-in-source' does.  It works for any var, but for a
function `cider-who-calls' is usually the better tool.

(fn &optional SYMBOL)" t)
(autoload 'cider-xref-fn-deps "cider-xref"
"Show all functions referenced by the var matching NS and SYMBOL.

(fn &optional NS SYMBOL)" t)
(autoload 'cider-xref-fn-refs-select "cider-xref"
"Display the references for NS and SYMBOL using completing read.

(fn &optional NS SYMBOL)" t)
(autoload 'cider-xref-fn-deps-select "cider-xref"
"Display the function dependencies for NS and SYMBOL using completing read.

(fn &optional NS SYMBOL)" t)
(register-definition-prefixes "cider-xref" '("cider-"))


;;; Generated autoloads from cider-xref-backend.el

(register-definition-prefixes "cider-xref-backend" '("cider-"))


;;; Generated autoloads from cider-xref-source.el

(register-definition-prefixes "cider-xref-source" '("cider-xref-"))


;;; Generated autoloads from cider-xref-tree.el

(autoload 'cider-who-calls "cider-xref-tree"
"Browse the callers of SYMBOL as an interactive tree.
Expand a node to reveal its own callers and walk the call graph upward.  Uses
the runtime `fn-refs' op, so it covers loaded Clojure-on-the-JVM code.

(fn &optional SYMBOL)" t)
(autoload 'cider-who-is-called "cider-xref-tree"
"Browse the callees of SYMBOL as an interactive tree.
Expand a node to reveal what it calls in turn and walk the call graph downward.
Uses the runtime `fn-deps' op, so it covers loaded Clojure-on-the-JVM code.

(fn &optional SYMBOL)" t)
(autoload 'cider-who-implements "cider-xref-tree"
"Browse the implementations of the protocol or multimethod SYMBOL.
For a protocol, lists the types that implement it; for a multimethod, lists its
dispatch values - on an expandable tree.

With cider-nrepl's `cider/who-implements' op this includes inline
`defrecord'/`deftype' implementers and jumps to each implementation's source.
Without it, a client-side fallback lists `extend'-style targets and dispatch
values only.  Clojure-on-the-JVM only.

(fn &optional SYMBOL)" t)
(autoload 'cider-type-protocols "cider-xref-tree"
"Browse the protocols implemented by the type SYMBOL.
Covers both `extend'-style and inline `defrecord'/`deftype' implementations.
Point should be on a type's name (a record/class) or a dotted class name; only
loaded Clojure-on-the-JVM code is visible.

(fn &optional SYMBOL)" t)
(autoload 'cider-protocols-with-method "cider-xref-tree"
"Browse the protocols that declare a method named METHOD.
With no argument, uses the (unqualified) name at point.  Only loaded
Clojure-on-the-JVM code is visible.

(fn &optional METHOD)" t)
 (autoload 'cider-who-map "cider-xref-tree" "CIDER call-graph keymap." nil 'keymap)
 (autoload 'cider-references-menu "cider-xref-tree" "Menu for CIDER's reference and call-graph queries." t)
(register-definition-prefixes "cider-xref-tree" '("cider-xref-tree--"))


;;; Generated autoloads from nrepl-bencode.el

(register-definition-prefixes "nrepl-bencode" '("nrepl-"))


;;; Generated autoloads from nrepl-client.el

(register-definition-prefixes "nrepl-client" '("nrepl-"))


;;; Generated autoloads from nrepl-dict.el

(register-definition-prefixes "nrepl-dict" '("nrepl-"))

;;; End of scraped data

(provide 'cider-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cider-autoloads.el ends here
