;;; eldoc-box-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eldoc-box.el

(autoload 'eldoc-box-help-at-point "eldoc-box" "\
Display documentation of the symbol at point." t)
(autoload 'eldoc-box-hover-mode "eldoc-box" "\
Display hover documentations in a childframe.

The default position of childframe is upper corner.

This is a minor mode.  If called interactively, toggle the
`Eldoc-Box-Hover mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `eldoc-box-hover-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'eldoc-box-hover-at-point-mode "eldoc-box" "\
A convenient minor mode to display doc at point.

You can use \\[keyboard-quit] to hide the doc.

This is a minor mode.  If called interactively, toggle the
`Eldoc-Box-Hover-At-Point mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `eldoc-box-hover-at-point-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "eldoc-box" '("eldoc-box-"))

;;; End of scraped data

(provide 'eldoc-box-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eldoc-box-autoloads.el ends here
